# NumPy exercises

We are going to practice NumPy skills and basic syntax.

We put here also some examples that were not in the tutorial on purpose. Try to use google and offial NumPy documentation to solve these exercises.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np
print(np.__version__)
np.__config__.show()

1.18.5
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Sherry/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Users/Sherry/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Sherry/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\m

#### 3. Create a null vector of size 10 (★☆☆)

In [33]:
a = np.zeros((10), np.int16)
a

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [34]:
a[4]=1
a

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0], dtype=int16)

#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆)

In [87]:
#b= np.random.randint(10,50, size=(1,10))
#print(b)
Z = np.arange(10,50)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8.  Reverse a vector (first element becomes last) (★☆☆)

In [88]:
#print("Original array:")
#print(b)
#print("Reverse array:")
#c = b[::-1]
#print(c)
#c = b.reverse()
#print(c)
########not working from all 3 here ???
# using flipud method to reverse 
#c = np.flipud(b) 
# printing result 
#print(str(c)) 
#print("final array", str(c)) 

Z= Z[::-1]
print (Z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [45]:
d = np.random.randint(0,9, size=(3,3))
print(d)
#not sure most recent:?
#Z = np.arange(9).reshape(3,3)

[[2 0 7]
 [4 0 0]
 [0 6 0]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆)

In [92]:
e = np.array([1,2,0,0,4,0])
print(e>0)
#create a nonzero array
nz= np.nonzero([1,2,0,0,4,0]) 
print(nz)
#note, identity matrix
idm = np.eye(3)   #3x3 
print(idm)

[ True  True False False  True False]
(array([0, 1, 4], dtype=int32),)
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [94]:
f= np.random.randint(0,9, size=(3,3,3))
print(f)

#not sure if this is what looking for , code does not work
#uniform_Matrix = random.uniform((3,3,3))
#print(uniform_Matrix)

[[[7 1 6]
  [1 3 0]
  [5 5 2]]

 [[2 7 4]
  [3 6 7]
  [8 2 0]]

 [[5 3 6]
  [6 5 4]
  [1 0 4]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [96]:
g = np.random.randint(0,9, size=(10,10))
print(g)
print(np.min(g))
print(np.max(g))
#other way
print(g.min(),g.max())

[[6 5 8 7 1 7 1 3 3 5]
 [8 7 1 1 6 4 5 4 4 6]
 [2 0 6 8 7 1 2 7 8 0]
 [7 6 8 6 4 2 4 5 6 4]
 [2 6 3 6 3 8 8 6 1 2]
 [6 5 7 3 8 1 6 7 8 4]
 [6 6 2 2 0 7 3 8 2 6]
 [4 7 2 4 5 2 8 5 0 7]
 [5 3 1 7 5 5 3 2 8 3]
 [1 3 3 7 2 8 3 8 3 0]]
0
8
0 8


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [98]:
h = np.random.randint(0,9, size=(1,30))
print(h)
print(np.mean(h)) 
#or 
print(h.mean())

[[8 2 5 0 0 7 0 4 7 6 0 3 4 8 5 6 1 1 8 3 2 5 1 1 3 2 6 3 0 2]]
3.433333333333333
3.433333333333333


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [100]:
output = np.ones((5,5), dtype='int16')
print(output)
#create smaller 0 matrix
z = np.zeros((3,3), dtype='int16')
print(z)
output[1:4,1:4] =z
print('final answer')
print(output)

#better way
Z= np.ones((10,10))
Z[1:-1,1:-1]=0   # get half of this,top and left, how does right and bottom?
print(Z)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]
final answer
[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [77]:
i = np.ones((5,5), dtype='int16')
print(i) #0:5,0 fills in the first column of zeros 
#print(a[2:4, 0:2]) 
#print(a[[0,1,2,3],[1,2,3,4]])  #rows from 0-3 , and col from 1to 4
i[0:5, 0] = 0
i[0:5,4]= 0
i[0,1:4]=0
i[4,1:4]= 0
print(i)
#i[[0:5, 0],[0:5,4]]= 0
#print(i)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[0 0 0 0 0]
 [0 1 1 1 0]
 [0 1 1 1 0]
 [0 1 1 1 0]
 [0 0 0 0 0]]


#### 17. What is the result of the following expression? (★☆☆)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

nan
False
False
nan
True
False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [101]:
#j = np.zeros((5,5), dtype='int16')
#print(j)
Z = np.diag(1+np.arange(4), k = -1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [104]:
#8x8 with checkerboard pattern
#Z = np.zeros ((8,8), dtype=int)
#Z[1::2, ::2]= 1
#Z[::2, 1::2] = 1
#print (Z)
#checkerboard matrix with a tile function
#array= np.array([[0,1], [1,0]])
#Z = np.tile(array,(4,4))
#print (Z)
print(np.unravel_index(100,(6,7,8)))

(1, 5, 4)


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [111]:
k= np.random.rand(5,5)
print(k)
kmax, kmin = k.max(), k.min()
#normalize formula
k =(k-kmin)/(kmax-kmin)
print(k)

[[0.44783727 0.13877617 0.2421227  0.32540038 0.56409538]
 [0.74125749 0.87036908 0.06249245 0.00888465 0.18828175]
 [0.9706652  0.677581   0.89393668 0.26361456 0.19793627]
 [0.87489755 0.61364547 0.38700177 0.61717275 0.74707535]
 [0.57688572 0.97053276 0.28073126 0.59032635 0.95206451]]
[[0.45639581 0.13505318 0.24250651 0.3290935  0.57727381]
 [0.76147603 0.89571829 0.05573807 0.         0.18652601]
 [1.         0.69526915 0.92022242 0.26485243 0.19656419]
 [0.90042671 0.62879294 0.39314282 0.63246039 0.76752509]
 [0.59057242 0.9998623  0.2826493  0.60454716 0.98066015]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [200]:
#numpy where and a numpy negative, not sure if giving indexes in questions?, this is the third and 8th place
a = np.random.random(size=10)
print(a)
a[2:8] = np.negative(a[2:8])
print(a)

[0.10397155 0.32594631 0.57474135 0.38288488 0.91957246 0.15570702
 0.21752489 0.93844767 0.4143076  0.90646946]
[ 0.10397155  0.32594631 -0.57474135 -0.38288488 -0.91957246 -0.15570702
 -0.21752489 -0.93844767  0.4143076   0.90646946]


#### 29. How to round away from zero a float array ? (★☆☆)

In [202]:
data = np.array([  1.60130719e-01,   9.93827160e-01,   3.63108206e-04])
print(data)
print(np.round(data, 2))

[1.60130719e-01 9.93827160e-01 3.63108206e-04]
[0.16 0.99 0.  ]


#### 30. How to find common values between two arrays? (★☆☆)

In [3]:
# create 2 arrays 
a = np.array([2, 4, 7, 1, 4]) 
b = np.array([7, 2, 9, 0, 5]) 
  
# Display the arrays 
print("Original arrays", a, ' ', b) 
  
# use the np.intersect1d method 
c = np.intersect1d(a, b) 
  
# Display result 
print("Common values", c) 

Original arrays [2 4 7 1 4]   [7 2 9 0 5]
Common values [2 7]


#### 32. Is the following expressions true? (★☆☆)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [203]:
#np.sqrt(-1) == np.emath.sqrt(-1)
#False

False

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [116]:
def generate():
    for x in range(10):
        yield x

Z= np.fromiter(generate(), dtype=float,count=-1)
print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [118]:
#linear space function, takes what to exclude
l = np.linspace(0,1,12, endpoint=True)[1:-1]
print(l)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [123]:
#tried with randint, gives error on sort(), int obj no sort
m =np.random.rand(1,10)
m.sort()
print(m)

[[0.07298901 0.20308188 0.47177421 0.55962711 0.653175   0.66672278
  0.68941888 0.80816412 0.8094795  0.82837881]]


#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [124]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
#two same shaped arrays, each taking in random values 
equal = np.allclose(A,B)
print(equal)

False


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [130]:
n= np.random.rand(10)
print(n)
n[n.argmax()] = 0
print(n)

[0.80331031 0.91996291 0.06441937 0.87861046 0.41175084 0.50562202
 0.44474928 0.08315354 0.81983131 0.29170442]
[0.80331031 0.         0.06441937 0.87861046 0.41175084 0.50562202
 0.44474928 0.08315354 0.81983131 0.29170442]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [138]:
o= np.arange(100) 
print(o)
v = np.random.uniform(0,100)
print(v)
index = (np.abs(o-v)).argmin()
print(o[index])


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
74.79964998052317
75


#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [143]:
p= np.arange(10, dtype=np.int32)
print(p)
p = p.astype(np.float32,copy=False)
print(p)

[0 1 2 3 4 5 6 7 8 9]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 59. How to sort an array by the nth column? (★★☆)

In [153]:
r = np.random.randint(0,10,(3,3)) #numbers 0-9, in 3x3
print(r)
print(r[r[:,1].argsort()])

[[9 7 0]
 [7 5 5]
 [5 1 1]]
[[5 1 1]
 [7 5 5]
 [9 7 0]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [154]:
s= np.random.randint(0,3,(3,10))
print(s)
print((~s.any(axis=0)).any())


[[0 0 1 1 1 2 1 1 1 2]
 [2 1 1 0 1 0 2 0 0 1]
 [1 1 1 0 2 2 2 0 0 0]]
False


#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [164]:
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 72. How to swap two rows of an array? (★★★)

In [169]:
#swaps first two rows
A = np.arange(25).reshape(5,5)
print(A)
A[[0,1]] = A[[1,0]]
print(A)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [175]:
Z = np.random.randint(0,2,100)
print ('original: ')
print (Z)
print('Negating a boolean: ')
print(np.logical_not(Z, out=Z))


Z = np.random.uniform(-1.0,1.0,10)
print ('original: ')
print (Z)
print ('Change the sign of float inplace: ')
print(np.negative(Z, out=Z))

original: 
[1 1 0 0 1 1 1 0 0 0 1 1 1 0 1 1 0 0 0 0 1 1 0 0 1 1 0 0 1 0 0 1 0 0 0 1 0
 1 1 0 0 1 1 1 1 1 1 1 0 0 1 0 1 0 0 0 1 0 0 0 0 1 1 0 1 0 0 0 0 0 1 1 0 1
 0 0 0 0 0 0 1 1 1 1 0 0 0 0 0 0 1 0 0 1 1 1 0 1 0 0]
Negating a boolean: 
[0 0 1 1 0 0 0 1 1 1 0 0 0 1 0 0 1 1 1 1 0 0 1 1 0 0 1 1 0 1 1 0 1 1 1 0 1
 0 0 1 1 0 0 0 0 0 0 0 1 1 0 1 0 1 1 1 0 1 1 1 1 0 0 1 0 1 1 1 1 1 0 0 1 0
 1 1 1 1 1 1 0 0 0 0 1 1 1 1 1 1 0 1 1 0 0 0 1 0 1 1]
original: 
[-0.62160409 -0.50027827  0.58503797  0.06027179 -0.0137135  -0.39116125
  0.46838921 -0.5969462  -0.83378423 -0.54350341]
Change the sign of float inplace: 
[ 0.62160409  0.50027827 -0.58503797 -0.06027179  0.0137135   0.39116125
 -0.46838921  0.5969462   0.83378423  0.54350341]


#### 83. How to find the most frequent value in an array?

In [182]:
Z = np.random.randint(0,10,50)
print (Z)
print('rank:', np.bincount(Z).argmax())


[8 3 1 3 6 2 0 5 2 9 8 0 1 9 7 9 9 3 0 4 7 4 2 7 4 3 5 4 1 3 2 8 9 5 7 3 2
 3 3 1 7 0 3 7 6 0 9 8 4 2]
rank: 3


#### 89. How to get the n largest values of an array (★★★)

In [188]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

# Slow
print (Z[np.argsort(Z)[-n:]])

# Fast
print (Z[np.argpartition(-Z,n)[:n]])

[9995 9996 9997 9998 9999]
[9997 9996 9999 9998 9995]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [195]:
# Author: Jaime Fernández del Río

Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)

[[0 0 0]
 [0 1 0]
 [0 1 1]
 [1 0 1]]


#### 97.(extra)Multiply a 5x3 matrix by a 3x2 matrix(real matrix product) 

In [113]:
Z = np.dot(np.ones((5,3)), np.ones((3,2)))
print(Z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


### 98.(extra) Make an array immutable (read-only)

In [125]:
Z= np.zeros(10)
Z.flags.writeable = False
Z[0] = 1
#would get an error 

ValueError: assignment destination is read-only

#### Consider a random 10X2 matrix representing cartesian coordinates, convert them to polar coordinates

In [126]:
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

[0.73304571 0.97721108 0.75882455 0.89615532 0.45234846 0.7810392
 1.13732106 0.67338617 0.59610123 0.15490951]
[0.29238155 0.84196893 0.25534849 1.09807959 0.50385456 0.82322444
 0.97326813 0.30774285 1.02760769 1.25346973]


#### Create a structered array with x and y coordinates covering the [0,1]x[0,1] area

In [131]:
Z = np.zeros((10,10), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,10),
                             np.linspace(0,1,10))
print(Z)

[[(0.        , 0.        ) (0.11111111, 0.        )
  (0.22222222, 0.        ) (0.33333333, 0.        )
  (0.44444444, 0.        ) (0.55555556, 0.        )
  (0.66666667, 0.        ) (0.77777778, 0.        )
  (0.88888889, 0.        ) (1.        , 0.        )]
 [(0.        , 0.11111111) (0.11111111, 0.11111111)
  (0.22222222, 0.11111111) (0.33333333, 0.11111111)
  (0.44444444, 0.11111111) (0.55555556, 0.11111111)
  (0.66666667, 0.11111111) (0.77777778, 0.11111111)
  (0.88888889, 0.11111111) (1.        , 0.11111111)]
 [(0.        , 0.22222222) (0.11111111, 0.22222222)
  (0.22222222, 0.22222222) (0.33333333, 0.22222222)
  (0.44444444, 0.22222222) (0.55555556, 0.22222222)
  (0.66666667, 0.22222222) (0.77777778, 0.22222222)
  (0.88888889, 0.22222222) (1.        , 0.22222222)]
 [(0.        , 0.33333333) (0.11111111, 0.33333333)
  (0.22222222, 0.33333333) (0.33333333, 0.33333333)
  (0.44444444, 0.33333333) (0.55555556, 0.33333333)
  (0.66666667, 0.33333333) (0.77777778, 0.33333333)
  (0.8888

#### Print the minimum and maximum representable value for each scalar type

In [132]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### How to print all the values of an array?

In [137]:
np.set_printoptions(threshold=sys.maxsize)  #np.nan did not work, need another os library?
Z1 = np.zeros((25,25))
print(Z1)

NameError: name 'sys' is not defined

### Create a structured array representing a position(x,y) and a color(r,g,b) 

In [139]:
#this has been depricated, but still prints
# need to say instead, typy,1 -> 1, type...
Z = np.zeros(10, [ ('position', [ ('x', float, 1),
                                   ('y', float, 1)]),
                    ('color',    [ ('r', float, 1),
                                   ('g', float, 1),
                                   ('b', float, 1)])])
print(Z)


[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


<ipython-input-139-3a6f5eca1821>:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  Z = np.zeros(10, [ ('position', [ ('x', float, 1),


##### Consider a random vector with the shape (100,2) representing coordinates, find point by point distances

In [140]:
Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0]), np.atleast_2d(Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

# Much faster with scipy
import scipy
# Thanks Gavin Heverly-Coulson (#issue 1)
import scipy.spatial

Z = np.random.random((10,2))
D = scipy.spatial.distance.cdist(Z,Z)
print(D)

[[0.         0.6618174  0.44850159 0.80956203 0.26235673 0.79214844
  0.4588362  0.51910898 0.18053915 0.51218865]
 [0.6618174  0.         0.32981472 0.3045665  0.62586457 0.98692198
  0.83003027 0.30474822 0.5740271  0.6663609 ]
 [0.44850159 0.32981472 0.         0.6061575  0.54774258 1.04462933
  0.78780624 0.43822603 0.45501888 0.70667303]
 [0.80956203 0.3045665  0.6061575  0.         0.67032031 0.84926488
  0.80428652 0.29726514 0.66514055 0.59183975]
 [0.26235673 0.62586457 0.54774258 0.67032031 0.         0.54190219
  0.2409049  0.37766826 0.10367835 0.25049719]
 [0.79214844 0.98692198 1.04462933 0.84926488 0.54190219 0.
  0.34597085 0.68298799 0.64450423 0.33867281]
 [0.4588362  0.83003027 0.78780624 0.80428652 0.2409049  0.34597085
  0.         0.54391311 0.34090151 0.2247665 ]
 [0.51910898 0.30474822 0.43822603 0.29726514 0.37766826 0.68298799
  0.54391311 0.         0.36802133 0.36314805]
 [0.18053915 0.5740271  0.45501888 0.66514055 0.10367835 0.64450423
  0.34090151 0.36802

#### Consider the following file:

1,2,3,4,5
6,,,7,8
,,9,10,11

###### How to read it?

In [144]:
#q = np.genfromtxt("missing.dat", delimiter=",")

#### What is the equivalent of enumerate for numpy arrays?

In [146]:
Z = np.arange(9).reshape(3,3)
print(Z)
for index, value in np.ndenumerate(Z):
    print(index, value)
for index in np.ndindex(Z.shape):
    print(index, Z[index])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### Create a generic 2D Gaussian-like array

In [147]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### How to randomly place p elements in a 2D array?

In [148]:
n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print (Z)

[[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### Subtract the mean of each row of a matrix

In [150]:
X = np.random.rand(5, 10)

# Recent versions of numpy
Y = X - X.mean(axis=1, keepdims=True)

# Older versions of numpy
#Y = X - X.mean(axis=1).reshape(-1, 1)
Y

array([[-0.33552645,  0.39059303, -0.28745561, -0.19358215, -0.28916386,
        -0.42764759,  0.32004221,  0.3786791 ,  0.22632177,  0.21773956],
       [ 0.11383243,  0.2575319 , -0.38954719, -0.47827573, -0.5086106 ,
         0.26778271,  0.22471793,  0.23193737, -0.07040969,  0.35104087],
       [ 0.33210085, -0.13959747, -0.37973635, -0.46860565,  0.26204583,
        -0.00839403,  0.27600188,  0.29521992, -0.32550794,  0.15647294],
       [-0.3744066 ,  0.37920801, -0.19002391,  0.31407585, -0.19079946,
        -0.45327907,  0.25592351,  0.42485873,  0.37054994, -0.53610699],
       [ 0.33012981,  0.30729251, -0.02737188, -0.53896903, -0.14125283,
        -0.33728211,  0.37537554,  0.25536386,  0.10048163, -0.3237675 ]])

#### Find the nearest value from a given value in an array

In [156]:
Z = np.random.uniform(0,1,10)
print(Z)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print(m)

[0.08344233 0.19085318 0.09600761 0.70295982 0.84744294 0.04133615
 0.16260141 0.87603478 0.32888263 0.93366808]
0.32888262710214033


#### Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)?

In [158]:
Z = np.ones(10) 
print(Z)
I = np.random.randint(0,len(Z),20)
print(I)
Z += np.bincount(I, minlength=len(Z))
print(Z) 
#note not sure if working or bc reduced size,
#random which numbers adding one to
#thus, may even reuse a number 

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[3 4 9 5 0 9 5 1 2 9 5 6 0 2 6 9 3 0 1 6]
[4. 3. 3. 3. 2. 4. 4. 1. 1. 5.]


#### Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors

In [159]:
w,h = 16,16
I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
F = I[...,0]*256*256 + I[...,1]*256 +I[...,2]
n = len(np.unique(F))
print(np.unique(I))

[0 1]


#### Considring a four dimensions array, how to get sum over the last two axis at once?

In [160]:
A = np.random.randint(0,10,(3,4,3,4))
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[52 66 47 46]
 [49 57 53 57]
 [55 72 43 61]]


#### Consdering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset indices?

In [162]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

[0.57624734 0.60433967 0.34857295 0.56652674 0.55282107 0.46166068
 0.24863238 0.53180479 0.48256771 0.52057184]


#### How to get the diagonal of a dot product?

In [163]:
A = np.random.randint(0,10,(3,3))
B= np.random.randint(0,10,(3,3))
#Slow version

np.diag(np.dot(A, B))

# Fast version
np.sum(A * B.T, axis=1)

# Faster version
np.einsum("ij,ji->i", A, B)

array([ 62,  93, 114])

#### Consider an array of dimension (5,5,3), how to multiply it by an array with dimensions (5,5)

In [167]:
A = np.ones((5,5,3))
print(A)
B = 2*np.ones((5,5))
print('This is B')
print(B)
print('This is result')
print(A * B[:,:,None])

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]
This is B
[[2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]]
This is result
[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### Consider a set of 10 triplets descibing 10 trianges (with shared vertices), find the set of unique line segments composing all the triangle

In [171]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)


[( 1, 44) ( 1, 62) ( 3, 49) ( 3, 76) ( 5, 18) ( 5, 43) ( 5, 87) ( 5, 97)
 (10, 34) (10, 59) (18, 97) (21, 84) (21, 91) (21, 97) (21, 99) (26, 62)
 (26, 96) (34, 59) (43, 87) (44, 62) (49, 76) (50, 54) (50, 59) (54, 59)
 (57, 60) (57, 64) (60, 64) (62, 96) (84, 99) (91, 97)]


#### Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C?

In [172]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


#### How to compute averages using a sliding window over an array? 

In [173]:
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)
print(moving_average(Z, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1])

In [174]:
def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return np.lib.stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i]) ?


In [176]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[7.57136415 3.77321179 2.90858602 1.49007236 3.75048431 5.27050073
 1.54589823 4.1740464  3.49205505 0.31866878]


#### Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i]) ?

In [177]:
P0 = np.random.uniform(-10, 10, (5,2))
P1 = np.random.uniform(-10,10,(5,2))
p = np.random.uniform(-10, 10, (5,2))
print (np.array([distance(P0,P1,p_i) for p_i in p]))

[[ 2.97434524  1.85335504  1.13108165  3.10069406  2.06615408]
 [ 1.26113223  4.9873003   2.58608881  0.37872756  0.83829788]
 [ 0.20861592  4.28910937  4.3433177   4.27437427  0.59945739]
 [11.61567717  6.74416353  7.29144153  3.56574996 10.90313308]
 [ 3.02268593 13.51412202  6.12049647  7.69782016  8.65748374]]


#### Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a fill value when necessary)

In [178]:
#some of this is depricated but still runs
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)

[[7 1 4 2 5 8 3 3 8 5]
 [5 4 5 6 1 4 6 4 7 3]
 [9 5 1 3 0 0 2 9 9 5]
 [2 6 0 1 1 0 4 8 4 3]
 [7 9 1 8 4 8 2 4 0 2]
 [6 5 4 9 2 1 4 1 2 7]
 [3 0 8 1 3 9 2 8 9 4]
 [8 3 2 4 2 5 2 2 0 9]
 [5 4 4 1 1 5 5 6 6 6]
 [5 0 7 5 0 8 1 3 4 9]]
[[0 0 0 0 0]
 [0 7 1 4 2]
 [0 5 4 5 6]
 [0 9 5 1 3]
 [0 2 6 0 1]]


<ipython-input-178-f2b5781f38bf>:23: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  R[r] = Z[z]


#### Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], …, [11,12,13,14]] ?

In [180]:
Z = np.arange(1,15,dtype=int)

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return np.lib.stride_tricks.as_strided(a, shape=shape, strides=strides)
R = rolling(Z, 4)
print ('original: ')
print (Z)
print ('after strides: ')
print(R)

original: 
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]
after strides: 
[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### Compute a matrix rank

In [181]:
Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z) # Singular Value Decomposition
rank = np.sum(S > 1e-10)
print (rank)

10


####  Extract all the contiguous 3x3 blocks from a random 6x6 matrix

In [183]:
Z = np.random.randint(0,5,(6,6))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = np.lib.stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)

[[[[4 4 0]
   [3 0 4]
   [4 3 1]]

  [[4 0 3]
   [0 4 3]
   [3 1 2]]

  [[0 3 2]
   [4 3 0]
   [1 2 0]]

  [[3 2 0]
   [3 0 2]
   [2 0 3]]]


 [[[3 0 4]
   [4 3 1]
   [2 1 2]]

  [[0 4 3]
   [3 1 2]
   [1 2 0]]

  [[4 3 0]
   [1 2 0]
   [2 0 4]]

  [[3 0 2]
   [2 0 3]
   [0 4 4]]]


 [[[4 3 1]
   [2 1 2]
   [4 4 4]]

  [[3 1 2]
   [1 2 0]
   [4 4 0]]

  [[1 2 0]
   [2 0 4]
   [4 0 1]]

  [[2 0 3]
   [0 4 4]
   [0 1 1]]]


 [[[2 1 2]
   [4 4 4]
   [2 3 2]]

  [[1 2 0]
   [4 4 0]
   [3 2 0]]

  [[2 0 4]
   [4 0 1]
   [2 0 0]]

  [[0 4 4]
   [0 1 1]
   [0 0 0]]]]


#### Create a 2D array subclass such that Z[i,j] == Z[j,i]

In [184]:
# invalid syntax in this first i,j
class Symetric(np.ndarray):
    def __setitem__(self, (i,j), value):
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

SyntaxError: invalid syntax (<ipython-input-184-3553fb9a4cb4>, line 2)

#### Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once ? (result has shape (n,1))

In [185]:
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

# It works, because:
# M is (p,n,n)
# V is (p,n,1)
# Thus, summing over the paired axes 0 and 0 (of M and V independently),
# and 2 and 1, to remain with a (n,1) vector.

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


#### Consider a 16x16 array, how to get the block-sum (block size is 4x4) ?

In [ ]:
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print ('input array')
print (Z)
print ('block sum')
print (S)

#### How to implement the Game of Life using numpy arrays ?

In [187]:
# Author: Nicolas Rougier
def iterate(Z):
    # Count neighbours
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    # Apply rules
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)

#### Given an arbitrary number of vectors, build the cartesian product (every combinations of every item)

In [189]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


#### How to create a record array from a regular array ?

In [190]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')

#### Consider a large vector Z, compute Z to the power of 3 using 3 different methods

In [191]:
# NOte gives type error
#1 loops, best of 3: 1.53 s per loop
#1 loops, best of 3: 528 ms per loop
#1 loops, best of 3: 286 ms per loop
#Deprication warning even where got from 
#//anaconda/lib/python3.5/site-packages/ipykernel/__main__.py:2: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
#  from ipykernel import kernelapp as app

x = np.random.rand(5e7)

%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)


TypeError: 'float' object cannot be interpreted as an integer

#### Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B ?

In [192]:
# Author: Gabe Schwartz

A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = (C.sum(axis=(1,2,3)) >= B.shape[1]).nonzero()[0]
print(rows)

[0 1 2 5 6]


#### Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3])

In [193]:
# Author: Robert Kern

Z = np.random.randint(0,5,(10,3))
E = np.logical_and.reduce(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(Z)
print(U)

[[3 1 1]
 [1 1 0]
 [4 4 0]
 [3 3 2]
 [0 4 0]
 [2 0 3]
 [0 4 1]
 [3 3 2]
 [4 3 0]
 [2 2 4]]
[[3 1 1]
 [1 1 0]
 [4 4 0]
 [3 3 2]
 [0 4 0]
 [2 0 3]
 [0 4 1]
 [3 3 2]
 [4 3 0]
 [2 2 4]]


#### Convert a vector of ints into a matrix binary representation

In [194]:
# Author: Warren Weckesser

I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])

# Author: Daniel T. McDonald

I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function

In [196]:
# Author: Alex Riley
# Make sure to read: http://ajcr.net/Basic-guide-to-einsum/

A= np.arange(3)
B =  np.arange(12).reshape(3,4)
print (A)
#np.einsum('ii->', A)       # np.sum(A)
#np.einsum('i,i->i', A, B) # A * B
#np.einsum('i,i', A, B)    # np.inner(A, B)
#np.einsum('...i,j', A, B)    # np.outer(A, B)

[0 1 2]


#### Considering a path described by two vectors (X,Y), how to sample it using equidistant samples ?

In [90]:
# Author: Bas Swinckels

phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 # segment lengths
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                # integrate path
r_int = np.linspace(0, r.max(), 200) # regular spaced path
x_int = np.interp(r_int, r, x)       # integrate path
y_int = np.interp(r_int, r, y)


#### sample exercise lists, dictionaries

In [89]:
def instructorWithLongestName(instructors):
    '''
        instructorWithLongestName: takes in a list of values, with key, value pairs, 
                                   finds the name of the instructors in the list 
                                   returns the instructors with the longest name
        inputs: instructors, as list
        return: instructor , as dict list item
        Expected output:
            {name: "Jeremiah", course: "Data"}
            {name: "Domascus", course: "Web"}                            
    '''
    #print(any(isinstance(val, typ) for val in self))
    tempname =''
    iterCnt = 0
    instrData = []
    try:
        for instructor in instructors:
            for k, v in instructor.items():
                if k=='name':
                    if iterCnt > 0:
                        if len(v) > len(tempname):
                            tempname = v
                            instrData[0]= instructors[iterCnt]
                    else:
                        #first time through add value
                        tempname = v
                        instrData.append(instructors[iterCnt])
    
            iterCnt +=1  #keep track of instructor want to add
    finally:
        return instrData[0]

    
print(instructorWithLongestName([
  {'name': "Samuel", 'course': "iOS"},
  {'name': "Jeremiah",'course': "Data"},
  {'name': "Ophilia", 'course': "Web"},
  {'name': "Donald", 'course': "Web"}
]))
print(instructorWithLongestName([
  {'name': "Matthew", 'course': "Data"},
  {'name': "David", 'course': "iOS"},
  {'name': "Domascus", 'course': "Web"}
]))


{'name': 'Jeremiah', 'course': 'Data'}
{'name': 'Domascus', 'course': 'Web'}


#### Sample matrix exercise, returning a coordinate

In [ ]:
spots =   [
    # COLUMNS ARE X
    # 0    1    2    3    4    5
    ['s', 's', 's', 'S', 'R', 'M'], # 0 ROWS ARE Y
    ['s', 'M', 's', 'S', 'r', 'M'], # 1
    ['s', 'M', 's', 'S', 'r', 'm'], # 2
    ['S', 'r', 's', 'm', 'r', 'M'], # 3
    ['S', 'r', 's', 'm', 'r', 'M'], # 4
    ['S', 'r', 'S', 'M', 'M', 'S']  # 5
  ]
 vehicle = 'regular'


    
    
'''

print(whereCanIPark(
  [
    # COLUMNS ARE X
    # 0    1    2    3    4    5
    ['s', 's', 's', 'S', 'R', 'M'], # 0 ROWS ARE Y
    ['s', 'M', 's', 'S', 'r', 'M'], # 1
    ['s', 'M', 's', 'S', 'r', 'm'], # 2
    ['S', 'r', 's', 'm', 'r', 'M'], # 3
    ['S', 'r', 's', 'm', 'r', 'M'], # 4
    ['S', 'r', 'S', 'M', 'M', 'S']  # 5
  ],
  'regular'
))

print(whereCanIPark(
  [
    ['M', 'M', 'M', 'M'],
    ['M', 's', 'M', 'M'],
    ['M', 'M', 'M', 'M'],
    ['M', 'M', 'r', 'M']
  ],
  'small'
))

print(whereCanIPark(
  [
    ['s', 's', 's', 's', 's', 's'],
    ['s', 'm', 's', 'S', 'r', 's'],
    ['s', 'm', 's', 'S', 'r', 's'],
    ['S', 'r', 's', 'm', 'r', 's'],
    ['S', 'r', 's', 'm', 'R', 's'],
    ['S', 'r', 'S', 'M', 'm', 'S']
  ],
  'motorcycle'
)) 
'''