**TASK:** import numpy

In [1]:
import numpy as np

**TASK:** define vector 'x' with three coordinates

In [2]:
x = np.array([1, 2, 3])  #vector is one dimensional?
x

array([1, 2, 3])

**TASK:** define (2 x 2) matrix 'A' 


In [140]:
A = np.array([[1,2],[3,4]])
A.shape

(2, 2)

**TASK:** define (2 x 2) matrix 'B'

In [141]:
B = np.array([[5,6],[7,8]])
B.shape

(2, 2)

**TASK:** check the type of 'x'

In [142]:
type(x)

numpy.ndarray

**TASK:** check the type of 'A'

In [143]:
type(A)

numpy.ndarray

**TASK:**  check the shape of 'x'


In [144]:
x.shape
#len(x)

(3,)

**TASK:** check the type of 'A'

In [145]:
type(B)  #already did A, maybe B, or shape of A?

numpy.ndarray

**TASK:** 

In [146]:
"""
Define function 'have_same_shape' which checks if two arrays have same shape.

PARAMS:
    array_1 (numpy.ndarray) - first array
    array_2 (numpy.ndarray) - second array
RETURN:
    True - if arrays have same shape
    False - if arrays do not have same shape

Also print 'Arrays must have same shape!' when returning False
"""

"\nDefine function 'have_same_shape' which checks if two arrays have same shape.\n\nPARAMS:\n    array_1 (numpy.ndarray) - first array\n    array_2 (numpy.ndarray) - second array\nRETURN:\n    True - if arrays have same shape\n    False - if arrays do not have same shape\n\nAlso print 'Arrays must have same shape!' when returning False\n"

In [147]:
def have_same_shape(array_1,array_2):
    #input two arrays, checks if same, return True or False
    try:
        if array_1.shape == array_1.shape:
            return True
        else:
            return False
    except AssertionError as error:
        return print(error)

**TASK:** call the function 'have_same_shape' with matrix 'A' and vector 'x' as inputs

In [148]:
have_same_shape(A,x)

True

**TASK:**  call the function 'have_same_shape' with matrix 'A' and matrix 'B' as inputs

In [149]:
have_same_shape(A,B)

True

**TASK:** 

In [150]:
"""
Define function 'matrix_addition' which perform matrix addition value by value.

PARAMS:
    A (numpy.ndarray) - first array
    B (numpy.ndarray) - second array
RETURN:
    C (numpy.ndarray) - new A+B array

In this task do not consider broadcasting.
Do not forget to check arrays shapes (you can use 'have_same_shape' function defined before)

"""


"\nDefine function 'matrix_addition' which perform matrix addition value by value.\n\nPARAMS:\n    A (numpy.ndarray) - first array\n    B (numpy.ndarray) - second array\nRETURN:\n    C (numpy.ndarray) - new A+B array\n\nIn this task do not consider broadcasting.\nDo not forget to check arrays shapes (you can use 'have_same_shape' function defined before)\n\n"

In [151]:
def matrix_addition(a,b):
    #input 2 arrays and adds together, error is not same shape (not considering braodcasting)arr = np.empty((0,3), int)
    try:
        c = a + b
        return c
    except AssertionError as error:
        return print(error)
    

**TASK:** call the function 'matrix_addition' with matrix 'A' and matrix 'B' as inputs

In [152]:
#C = A + B
C = matrix_addition(A,B)
C

array([[ 6,  8],
       [10, 12]])

**TASK:** 

In [153]:
"""
Define 'multiple_matrix_adition' function that takes list of arrays as the input and perform array addition

PARAMS:
   lst_of_arr (list) - list of numpy.ndarrays
RETURN:
    NEW_ARRAY (numpy.ndarray) - new array

Use 'matrix_addition' function defined before.
"""

"\nDefine 'multiple_matrix_adition' function that takes list of arrays as the input and perform array addition\n\nPARAMS:\n   lst_of_arr (list) - list of numpy.ndarrays\nRETURN:\n    NEW_ARRAY (numpy.ndarray) - new array\n\nUse 'matrix_addition' function defined before.\n"

In [154]:
def multiple_matrix_addition(lst_of_arr):
    #takes list of arrays as input and perform array addition, return new array
    #define an empty numpy array
    #NEW_ARRAY = np.empty((2,2), int)  (note will error if not same shape)
    cnt = 0
    try:
        for arr in lst_of_arr:
            if cnt == 0:
                NEW_ARRAY = arr
            else:
                NEW_ARRAY += arr
            cnt +=1
        print(cnt)
        return NEW_ARRAY
    except AssertionError as error:
        return print(error)

**TASK:** call the function 'multiple_matrix_addition' with matrix [A,A,B,B,B] as input


In [155]:
C = multiple_matrix_addition([A,A,B,B,B] )
C
'''
first time through
5
array([[17, 22],
       [27, 32]])
'''

5


'\nfirst time through\n5\narray([[17, 22],\n       [27, 32]])\n'

**TASK:** 

In [156]:
"""
Define function 'can_multiply' that checks if two arrays (matrices) can be multiplied

PARAMS:
   array_a (numpy.ndarray) - first array
   array_b (numpy.ndarray) - second array
RETURN:
    True - if arrays can be multiplied, also print the shape of the new array
    False - if arrays can not be multiplied, also print 'Matrices can not be multiplied.'
    
"""

"\nDefine function 'can_multiply' that checks if two arrays (matrices) can be multiplied\n\nPARAMS:\n   array_a (numpy.ndarray) - first array\n   array_b (numpy.ndarray) - second array\nRETURN:\n    True - if arrays can be multiplied, also print the shape of the new array\n    False - if arrays can not be multiplied, also print 'Matrices can not be multiplied.'\n    \n"

In [157]:
#https://www.programiz.com/python-programming/examples/multiply-matrix
def can_multiply(array_a,array_b):
    #checks if two arrays (matrices) can be multiplied
    #The first row can be selected as X[0]. 
    #And, the element in first row, first column can be selected as X[0][0].
    #Do length checks 2x3 number of columns A,   3x2   number of rows of B , should be equal to multiply
    try:
        #array_a_col = len(array_a[0])  #gets the length of the first row which is the number of columns
        #array_b_row = len(array_b[0][0])  #gets the length of the columns which is the number of rows: does not work
        #if array_a.shape[1] == array_b[0]:  #does not work says ambiguous
        row_a, col_a = array_a.shape  #row,col  x row,col
        row_b, col_b = array_b.shape
        #print(row_b)
        #print(col_a)
        if  col_a == row_b:
            return True
        else:
            return False
        
    except AssertionError as error:
        return print(error)

**TASK:** call the function 'can_multiply' with matrix 'A' and 'B' as inputs

In [158]:
can_multiply(A,B)

True

**TASK:**  define matrix (3 x 2) matrix C

In [159]:
C = np.array([[1,2],[3,4],[5,6]])
#C.shape
C.shape

(3, 2)

**TASK:**  call the function 'can_multiply' with matrix 'A' and 'C' as inputs

In [160]:
can_multiply(A,C)   # 2x2   with 3x2

False

**TASK:**  call the function 'can_multiply' with matrix 'C' and 'A' as inputs (now C,A not A,C). Do you know why is the result different?

In [161]:
can_multiply(C,A)

True

**TASK:** 

In [162]:
"""
Define function 'matrix_multiplication' that multiply two numpy.ndarrays

PARAMS:
   array_a (numpy.ndarray) - first array
   array_b (numpy.ndarray) - second array
RETURN:
    NEW_ARRAY (numpy.ndarray) - new A * B array
    
Do not forget to check if two matrices can be multiplied.

"""

"\nDefine function 'matrix_multiplication' that multiply two numpy.ndarrays\n\nPARAMS:\n   array_a (numpy.ndarray) - first array\n   array_b (numpy.ndarray) - second array\nRETURN:\n    NEW_ARRAY (numpy.ndarray) - new A * B array\n    \nDo not forget to check if two matrices can be multiplied.\n\n"

In [163]:
def matrix_multiplication(array_a, array_b):
    #multiply matrices
    try:
        if can_multiply(array_a, array_b):
            NEW_ARRAY = array_a.dot(array_b)
            return NEW_ARRAY
        else:
            return False
    except AssertionError as error:
        return print(error)    

**TASK:**  call the function 'matrix_multiplication' with matrix 'C' and 'B' 


In [164]:
D = matrix_multiplication(C,B)
D

array([[19, 22],
       [43, 50],
       [67, 78]])

**TASK:** call the function 'matrix_multiplication' with matrix 'A' and 'C' 

In [165]:
matrix_multiplication(A,C)

False